"""
Matching Engine — the referee.

Algorithm: Price-Time Priority (FIFO)
  1. Best price wins
  2. Equal price → earliest order wins

This is the same algorithm used by most real exchanges
(NYSE, NASDAQ use variants of this).
"""
from __future__ import annotations
from .models import Order, Side, Trade
from .order_book import OrderBook


class MatchingEngine:
    __slots__ = ("book", "_next_order_id", "recent_trades")

    def __init__(self) -> None:
        self.book = OrderBook()
        self._next_order_id: int = 0
        # Ring buffer of recent trades (capped at 50)
        # We only need the last N trades for the UI feed
        self.recent_trades: list[Trade] = []

    # ──────────────────────────────────────────────
    # Public interface
    # ──────────────────────────────────────────────

    def submit(self, side: Side, price: float, quantity: int) -> list[Trade]:
        """
        Submit a new order. Returns all trades generated by this order.
        The order (or its remainder) rests in the book if unmatched.
        """
        order_id = self._next_id()
        order = Order.create(order_id, side, price, quantity)
        trades = self._match(order)
        return trades

    def snapshot(self) -> dict:
        """Full state snapshot for WebSocket broadcast."""
        book_snap = self.book.snapshot(depth=10)
        last_trade = self.recent_trades[-1] if self.recent_trades else None

        return {
            "bids":       book_snap["bids"],
            "asks":       book_snap["asks"],
            "last_trade": {
                "price":    last_trade.price,
                "quantity": last_trade.quantity,
                "ts":       last_trade.timestamp_ms,
            } if last_trade else None,
            "trades": [
                {"price": t.price, "quantity": t.quantity, "ts": t.timestamp_ms}
                for t in self.recent_trades[-20:]   # last 20 for the ticker
            ],
        }

    # ──────────────────────────────────────────────
    # Core matching logic
    # ──────────────────────────────────────────────

    def _match(self, incoming: Order) -> list[Trade]:
        trades: list[Trade] = []
        remaining = incoming.quantity

        if incoming.side == Side.BUY:
            trades = self._fill_buy(incoming, remaining)
        else:
            trades = self._fill_sell(incoming, remaining)

        # Store recent trades — cap at 50 (ring buffer behaviour)
        self.recent_trades.extend(trades)
        if len(self.recent_trades) > 50:
            self.recent_trades = self.recent_trades[-50:]

        return trades

    def _fill_buy(self, incoming: Order, remaining: int) -> list[Trade]:
        trades: list[Trade] = []

        while remaining > 0:
            best_ask = self.book.best_ask()

            # No sellers, or cheapest seller is too expensive
            if best_ask is None or best_ask.price > incoming.price:
                # Rest the unfilled portion in the book
                leftover = Order.create(incoming.id, Side.BUY, incoming.price, remaining)
                self.book.add(leftover)
                break

            # ✅ Match found
            fill_qty = min(remaining, best_ask.quantity)
            trade = Trade(
                price=best_ask.price,
                quantity=fill_qty,
                buyer_id=incoming.id,
                seller_id=best_ask.id,
            )
            trades.append(trade)
            remaining -= fill_qty

            if fill_qty == best_ask.quantity:
                # Ask fully consumed — remove it
                self.book.pop_best_ask()
            else:
                # Ask partially filled — update remaining quantity
                self.book.reduce_quantity(best_ask.id, fill_qty)
                break

        return trades

    def _fill_sell(self, incoming: Order, remaining: int) -> list[Trade]:
        trades: list[Trade] = []

        while remaining > 0:
            best_bid = self.book.best_bid()

            # No buyers, or best buyer won't pay enough
            if best_bid is None or best_bid.price < incoming.price:
                leftover = Order.create(incoming.id, Side.SELL, incoming.price, remaining)
                self.book.add(leftover)
                break

            fill_qty = min(remaining, best_bid.quantity)
            trade = Trade(
                price=best_bid.price,
                quantity=fill_qty,
                buyer_id=best_bid.id,
                seller_id=incoming.id,
            )
            trades.append(trade)
            remaining -= fill_qty

            if fill_qty == best_bid.quantity:
                self.book.pop_best_bid()
            else:
                self.book.reduce_quantity(best_bid.id, fill_qty)
                break

        return trades

    # ──────────────────────────────────────────────
    # Helpers
    # ──────────────────────────────────────────────

    def _next_id(self) -> int:
        self._next_order_id += 1
        return self._next_order_id
